name: List Subfolders

on:
  workflow_dispatch:
    inputs:
      src_dir:
        description: 'Source Folder'
        required: false
        default: ''
      src_repository:
        description: 'Source Repository'
        required: true
        default: ''
      src_branch:
        description: 'Branch'
        required: false
        default: ''

jobs:
  list-folders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.src_repository }}
          ref: ${{ inputs.src_branch }}

      - name: List subfolders in database/data1
        run: |
          ROOT=${{ inputs.src_dir }}

          echo "Running command inside each subfolder in: $ROOT"
          echo ""

          # Loop through subdirectories
          count=0
          for dir in "$ROOT"/*/; do
            # Remove trailing slash for clean folder name
            folder=$(basename "$dir")

            echo "=== Folder: $folder ==="
            
            # Your command here:
            ls -la $(pwd)/$dir
            docker run --rm \
              -v $(pwd)/$dir:/app:rw \
              -v /tmp:/tmp \
              -t docker.io/aquasec/trivy:latest fs /app \
              --format "cyclonedx" \
              --scanners vuln,license \
              --output "/tmp/trivy-sbom-$folder.json"
            echo ""
            
            count=$((count+1))
            #if [ "$count" -ge 2 ]; then
            #  break
            #fi
          done

      - name: artifact name
        id: artifactname
        run: |
          out_name="${{ inputs.src_repository }}"
          out_name="${out_name//\//-}"  # Replace '/' with '-'
          echo "out_name=$out_name" >> $GITHUB_OUTPUT
  
      - name: Upload SBOM results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifactname.outputs.out_name }}
          path: /tmp/*.json
          if-no-files-found: warn
