name: Trivy Generate output SCA vs SBOM

on:
  workflow_dispatch:
    inputs:
      src_repository:
        description: 'Source Repository'
        required: true
        default: ''
      src_branch:
        description: 'Branch'
        required: false
        default: ''
      src_type:
        description: 'Project Type (java, python, dotnet) see https://cyclonedx.github.io/cdxgen/#/PROJECT_TYPES'
        required: false
        default: 'java'
      
env:
  OUTPUT_NAME: 'trivy_sca_vs_sbom'
jobs:
  sbom:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.src_repository }}
        ref: ${{ inputs.src_branch }}

    - name: Generate SBOM using Trivy
      run: |
          docker run --rm \
            -v "$(pwd)/${{ inputs.src_dir }}":/app:rw \
            -v /tmp:/tmp \
            -t docker.io/aquasec/trivy:latest fs /app \
            --format "cyclonedx" \
            --scanners vuln,license \
            --output "/tmp/trivy-sbom.json"

    - name: artifact name
      id: artifactname
      run: |
        out_name="${{ inputs.src_repository }}"
        out_name="${out_name//\//-}"  # Replace '/' with '-'
        echo "out_name=$out_name" >> $GITHUB_OUTPUT
          
    - name: Upload SBOM results
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.artifactname.outputs.out_name }}
        path: /tmp/*.json
        if-no-files-found: warn
